import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import Layout from '@/components/Layout'
import profilePic from "../../public/images/profile/developer-pic-1.png";
import AnimatedText from '@/components/AnimatedText'
import Link from 'next/link'
import { LinkArrow } from '@/components/Icons'
import LightBulb from "../../public/images/svgs/miscellaneous_icons_1.svg";
import TransitionEffect from '@/components/TransitionEffect'

export default function Home() {
  return (
    <>
      <Head>
        <title>My Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        
      </Head>
      <TransitionEffect />
      <main className='flex items-center text-dark w-full min-h-screen'>
        <Layout className='pt-0 md:pt-16 sm:pt-8' >
          <div className="flex items-center justify-between w-full lg:flex-col">
            <div className='w-1/2 md:w-full'>
              <Image src={profilePic} alt="EdgarRuto"className='w-full h-auto lg-hidden md:inline-block md:w-full' 
              priority
              sizes="(max-width: 768px) 100vw,
              (max-width: 1200px) 50vw, 33vw"
              />
            </div>
            <div className='w-1/2 flex flex-col items-center self-center lg:w-full lg:text-center'>
              <AnimatedText text="Telling Stories with Code and Design." className='!text-6x1 !text-left xl:!text-5xl
              lg:!text-center lg:!text=6xl mid:!text-5xl sm:!text-3xl lg:self-center mt-2
              '/>
              <p className='!text-xl font-light my-4 text-base md:text-sm sm:text-xs'>
              I am a junior developer who is passionate about creating impactful and engaging web applications. I use my skills in Next.js and web development to tell stories that resonate with users and showcase my expertise in the latest technologies. Here are some of my recent projects that demonstrate my abilities and potential.
              </p>
              <div className='!text-xl font-light my-4 text-base flex items-center self-start mt-2 lg:self-center '>
                <Link href="/dummy.pdf" target={"_blank"}
                className='flex items-center bg-black text-light p-2.5 px-6 rounded-lg text-lg font-semibold
                 hover:bg-light hover:text-dark border-2 border-solid border-transparent hover:border-dark md:p-2 md:px-4 md:text-base'
                 download={true}
                >Resume<LinkArrow 
                 className={"w-6 m1-1"}/></Link>

                <Link href="mailto:ruto.sigei@gmail.com" target={"_blank"}
                 className="mx-6 text-lg font-medium capitalize text-dark underline md:text-base"

                > Contact</Link>
              </div> 
            </div>
          </div>
        </Layout>
        <div className='absolute right-12 bottom-1 inline-block w-24 lg:hidden'>
          <Image src={LightBulb} alt="EdgarRuto" className='w-full  h-auto ' />
        </div>
        
      </main>
    </>
  )
}
 